name: peblo_story_buddy
description: Peblo AI Story Buddy Intern Task
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  provider: ^6.1.2
  confetti: ^0.7.0
  vibration: ^1.8.4

flutter:
  uses-material-design: true
